# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lobby_sessions', '0003_auto_20171030_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='comments',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
